### PR TITLE
R6 classes

### PR DESCRIPTION
**Pull request by eliocamp**
I remembered that I'd been working on porting the code to use R6 classes which made it easier to manage multiple concurrent requests (#55) and also should make it simpler to add new providers if necessary. 

This PR port the code into R6 and implements batch requests. 

The code to interact with the different service is now encapsulated in a `ecmwfr_service` class. Which has methods to submit requests, check for status, download and transfer. Most of the logic is common across services, in particular, the `$transfer()` method. Each service is then defined in its own service class which inherits from the generic class. Most of what changes is the parsing of the different status codes and the details on the URL strings that need to be sent. 

The batch request functionality is implemented in `wf_request_batch()`. Requests are initially on a queue until they are submitted. The function checks their status and when they are done and downloaded, they are moved into a "done" list and the next requests are moved into the queue. 

All tests pass except these ones:

----

```r
  # timeout trigger
  expect_message(
    wf_request(user = "11343",
               request = cds_request,
               time_out = -1,
               transfer = TRUE))
```

This fails because the request throws an error instead of a message when the transfer fails. Should I change that to a message?

---

```r
  # job test (can't run headless)
  expect_error(
    wf_request(user = "11343",
               request = cds_request,
               transfer = TRUE,
               job_name = "jobtest"))
```

This one fails because the transfer works. I don't remember why this should fail. 

--- 

```r
 # print archetype (test method)
 expect_message(print(ERA_interim))
```

This one fails because there is no print method for the archetype. I didn't touch this and this also fails in the current master?

---

In any case, since this is an important reworking, it would benefit from some more thorough testing in real life situations. Particularly the batch requests.

### CODE REVIEW

**Comment by khufkens** [comment]
Hi @eliocamp, seems like a nice addition, thanks!

The unit tests fail because you renamed the function last minute it seems and didn't update the test. 
 
This is the code used
```r
wf_batch_request(requests, user = "2088")
```
it should be:

```r
wf_request_batch(requests, user = "2088")
```
Do you fix or should I? This should address the issue I think.

**Comment by eliocamp** [comment]
Oh, I missed that one. 

I also merged changes in master.

**Comment by eliocamp** [comment]
webapi tests are failing because it cannot validate m credentials. I'm trying the website and is not loading. Is it down?

**Comment by khufkens** [comment]
I swear it wasn't me, I was just running unit tests. But yes it seems slow.

**Comment by khufkens** [comment]
The user here:
https://github.com/bluegreen-labs/ecmwfr/blob/aae6942dbd99b70fe28610dfc78d43336e80d1f7/tests/testthat/test_webapi.r#L399

should be info@bluegreenlabs.org

In the webapi test wrap setting the key in a `try()` statement.
https://github.com/bluegreen-labs/ecmwfr/blob/aae6942dbd99b70fe28610dfc78d43336e80d1f7/tests/testthat/test_webapi.r#L27

and delete all "failed" set key commands, as they now call an interface which doesn't work well with the unit tests.
https://github.com/bluegreen-labs/ecmwfr/blob/aae6942dbd99b70fe28610dfc78d43336e80d1f7/tests/testthat/test_webapi.r#L47

This should clear all unit tests on my end.

**Pull request merged**
